nginxserver {
    listen 10005;
    location /api/ {
        proxy_pass http://192.168.0.206:10004/api/;
    }
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}